# Generated by Django 4.2.7 on 2023-12-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_bodega_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
