# Generated by Django 4.2.7 on 2023-12-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_bodega_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
