# Generated by Django 4.2.7 on 2023-12-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_producto_referencia_idproveedor_transacciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='lote',
            field=models.CharField(max_length=30),
        ),
    ]
