# Generated by Django 5.0.2 on 2024-03-31 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_bodega_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencia',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
