# Generated by Django 5.0.2 on 2024-03-31 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_referencia_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencia',
            name='IdReferencia',
        ),
    ]
